### ISSUE TITLE
E-mail administrators about new offers

### ISSUE THREAD

**Issue by odarriba** [odarriba/elixir_jobs#3]
When someone submit a new offer, administrators should receive an e-mail telling that there is one new job offer pending review, and with the title/company name.

I'm personally fan of Mailgun, as I used it before and it's free for low quantity of emails/month. But I suppose using a standard mail library in Elixir is enough, as all providers has SMTP support.

**Comment by mnussbaumer** [comment]
I can do this. My idea was to use bamboo with the SMTP extension (I usually use sendgrid), and then it's just a matter of having the correct environment variables for the one being used and any provider will work?

**Comment by odarriba** [comment]
Of course! 

Remember that on production we use environment variables, while in development is on a secrets file.
