### ISSUE TITLE
Location is missing from RSS feed

### ISSUE THREAD

**Issue by huyz** [odarriba/elixir_jobs#7]
It's pretty important to have the location for each job in the RSS feed

**Comment by Medusalix** [comment]
I'd like to work on this :smile:

**Comment by odarriba** [comment]
Then do it!

Assigned to @Medusalix  🎉

**Comment by Medusalix** [comment]
![rss](https://user-images.githubusercontent.com/8124898/30985576-e7febb08-a490-11e7-9e33-78f6bb3fd319.png)

Got it working :smiley:. If you don't mind, I'll submit the PR on October 1st ready for the Hacktoberfest :smile:.

**Comment by odarriba** [comment]
Yeah of course!

Thanks a lot for fixing this! ❤️
