### ISSUE TITLE
Increase description length

### ISSUE THREAD

**Issue by odarriba** [odarriba/elixir_jobs#8]
We are getting some requests about 500 characters not being enough for some people.

Maybe we can increase the limit while doing some changes:

1. Show full description on `OfferController#show`
1. Show short description on `OfferController#index` and `OfferController#search`

The tricky thing is making a good cut of the description.

My idea was to get some cut tag (something like `<!-- READ MORE -->`) which should be added in the offer while approving to select in which point you want to cut the description.

**Comment by kelvinst** [comment]
What could be a good new limit for it? 1000?

**Comment by kelvinst** [comment]
And what about one more field for it? We still forcing the length of the description and use it on the `#index` and `#search` actions, and create a `more_details` with 1000 chars that allows publishers to put more details on the offers when needed, and show it on `#show`.

**Comment by odarriba** [comment]
Yeah! I think that's a good limit 😄 .

About the "cutting tag", I said that because if it's printed to HTML it won't be seen in the browser, but in reality we can choose anyone (that is not a common word or similar) as it can be removed.

Also, adding a "See more" link or similar form listings.

About adding an extra field, I'm not sure if that's a good idea, as the source of knowledge of an offer is the one who post it, which doesn't have to be the moderator.

**Comment by savekirk** [comment]
Adding an extra field, `summary`, can also be useful. Most of the first paragraphs of the job offer descriptions can be used as a summary for the job posting. 

So the `index` page displays the job info with the `summary` without the description and `show` will display the full job listing

Images below give a visual representation. 

### Job posting
![Job posting](https://user-images.githubusercontent.com/1415994/30994558-394b7222-a4bd-11e7-976e-af150035b5a7.png)

### Job listings
![Job listings](https://user-images.githubusercontent.com/1415994/30994557-3943c14e-a4bd-11e7-8e84-776eb4188668.png)


.

**Comment by odarriba** [comment]
@kelvinst @savekirk Ops! I didn't understand that the first time, sorry about that!

I think that could great, but we should specify in the placeholder the max length and that it will be shown in the listings.

Also, it makes sense to me that this new field should be text-only, not markdown (so the listings are clearer). What do you think?

Anyone wants to take care of this?

Thanks to both for this! <3

**Comment by savekirk** [comment]
@odarriba I will work on it. I suggest we limit the summary to `150` characters.

**Comment by odarriba** [comment]
Assigned to @savekirk then!

I'm not sure about the limit, let's try when implementing, because 3/4 lines of description in listings looks good to me, but we can see and come to an agreement (it's not only my call really).

Thanks! <3
